name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger the build job only on version tags (e.g., v1.0.0, v2.0.0)
  pull_request:
    branches:
      - main

env:
  project_name: semantiva_audio # Define a global variable for the project name
  python_version: '3.10.12'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies using PDM
        run: |
          pdm install

      - name: Run pylint
        run: |
          pdm run pylint ${{ env.project_name }} --fail-under=7.5

      - name: Run mypy
        run: |
          pdm run mypy .

      - name: Run black
        run: |
          pdm run black --check ${{ env.project_name }}

  test:
    runs-on: ubuntu-latest
    needs: linting  # Ensure that the test job runs after linting job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies using PDM
        run: |
          pdm install

      - name: Run pytest with coverage report
        run: |
          pdm run coverage run -m pytest --maxfail=1 -q -s
        
      - name: Display coverage report
        run: |
          pdm run coverage report

  build:
    runs-on: ubuntu-latest
    needs: test  # Ensure the build job runs after the test job completes successfully
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/semantiva-audio
    
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')  # Run only for tag pushes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies using PDM
        run: |
          pdm install

      - name: Build the package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml  # Update version in pyproject.toml
          echo "Building version: $VERSION"
          pdm build  # Build the package (sdist and wheel)

      - name: Publish to PyPI
        run: |
          pdm publish --repository pypi
